### PR TITLE
ENH: Update ITK CI tags to v5.2rc02

### PR DESCRIPTION
**Pull request by tbirdso**
Update ITK CI to reference ITK `master` branch as of 02-10-2021.

### CODE REVIEW

**Review by thewtex — CHANGES_REQUESTED** [review]
Could these please be updated to the recently tagged version, `v5.2rc02`?

**Review by dzenanz — APPROVED** [review]

**Review by thewtex — APPROVED** [review]
Thanks!

**Comment by dzenanz** [comment]
build-test-documentation (ubuntu-18.04) ran into:
```text
Run sed -i "6559d" /opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/sphinx/domains/cpp.py
  sed -i "6559d" /opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/sphinx/domains/cpp.py
  shell: /bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.8.7/x64
sed: can't read /opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages/sphinx/domains/cpp.py: No such file or directory
Error: Process completed with exit code 2.
```

**Comment by tbirdso** [comment]
Looks like `build-test-documentation (ubuntu-18.04)` is failing in other PRs as well rather than stemming from these changes. See [PR 193 checks](https://github.com/InsightSoftwareConsortium/ITKExamples/pull/193/checks?check_run_id=1865385875).

**Comment by tbirdso** [comment]
Seeing failures aligning with [Issue 178](https://github.com/InsightSoftwareConsortium/ITKExamples/issues/178) again. Is this a blocking issue?

**Comment by mseng10** [comment]
> Looks like `build-test-documentation (ubuntu-18.04)` is failing in other PRs as well rather than stemming from these changes. See [PR 193 checks](https://github.com/InsightSoftwareConsortium/ITKExamples/pull/193/checks?check_run_id=1865385875).

`build-test-documentation` is fixed in #187

**Comment by dzenanz** [comment]
Time to rebase other PRs on top of this.

**Pull request merged**
