### PR TITLE
BUG: Superbuild installs ITK Python 5.2.2 prerelease

### PR DESCRIPTION
**Pull request by tbirdso**
PR addresses CMake build failure seen in [Issue 201](https://github.com/InsightSoftwareConsortium/ITKExamples/issues/201).

### CODE REVIEW

**Review by dzenanz — APPROVED** [review]
It looks like there is some temporary issue with test data server.

**Comment by thewtex** [comment]
> It looks like there is some temporary issue with test data server.

@brianhelba @mgrauer example issue.

**Comment by mgrauer** [comment]
I don't follow the details, but I look forward to improving the situation!

🛠️

**Comment by thewtex** [comment]
@tbirdso thanks for submitting this!

Checking the error:

>   Could not find a version that satisfies the requirement itk>=5.2rc2 (from versions: 4.12.0.post1, 4.13.0, 4.13.1.post1, 4.13.2, 4.13.2.post1, 5.0a1, 5.0a2, 5.0b1, 5.0b3, 5.0rc1, 5.0rc2, 5.0.0, 5.0.0.post1, 5.0.1, 5.1b1, 5.1rc1.post1, 5.1rc2, 5.1rc3, 5.1.0, 5.1.0.post1, 5.1.0.post2, 5.1.0.post3, 5.1.1, 5.1.1.post1, 5.1.2)
No matching distribution found for itk>=5.2rc2

which is listing other pre-releases, I think we may be seeing the pip installed not being compatible with the ITK 5.2 packages. The ITK 5.2 upgraded from `manylinux1` to `manylinux2014`. The python we are using is the system python, which is relatively old (python 3.6). pip ships with python. I installed miniconda / python 3.8 and configured the build to use that. Let's see if that addresses the issue tomorrow. If not, let's merge this. We could avoid the minor side effect of, e.g. using pre-release versions of other packages like matplotlib when not intended.

**Comment by tbirdso** [comment]
@thewtex Looks like the issue is still present in the most recent [nightly build](https://open.cdash.org/viewBuildError.php?type=1&buildid=7067297):
> ERROR: Could not find a version that satisfies the requirement itk>=5.2rc2 (from versions: 4.12.0.post1, 4.13.0, 4.13.1.post1, 5.0a1, 5.0a2, 5.0b1, 5.0b3, 5.0rc1, 5.0rc2, 5.0.0, 5.0.0.post1, 5.0.1, 5.1rc1.post1, 5.1rc2, 5.1rc3, 5.1.0, 5.1.0.post1, 5.1.0.post2, 5.1.0.post3, 5.1.1, 5.1.1.post1, 5.1.2)
ERROR: No matching distribution found for itk>=5.2rc2

As you mentioned we are also seeing a `pip` version warning, though I'm not sure that this is a blocking issue:
> WARNING: You are using pip version 19.2.3, however version 21.0.1 is available.

**Comment by thewtex** [comment]
Checking on the system, the version of pip is newer in the conda environment, but not the superbuild virtual environment. Let's try https://github.com/InsightSoftwareConsortium/ITKExamples/pull/211

**Comment by tbirdso** [comment]
@thewtex Testing locally in a conda Python 3.8 environment with the latest `pip` (v21.0.1), the command `python -m pip install itk>=5.2.rc2` still installs ITK 5.1.2.

If we are trying to avoid installing prerelease versions other than ITK, would it be acceptable to simply install ITK in a separate call to `pip`? I.e. `pip install matplotlib ; pip install --pre itk`

**Comment by tbirdso** [comment]
Closing this PR as it appears [Issue 201](https://github.com/InsightSoftwareConsortium/ITKExamples/issues/201) is resolved. The [ITKExamples public docs](https://itk.org/ITKExamples/src/index.html) show that they were last built successfully on today's date (03/01/21).

**Pull request closed without merging**
