### PR TITLE
ENH: Update submodules to the latest master branches

### PR DESCRIPTION
**Pull request by hjmjohnson**
The submodules were out of date and are causing problems wiht reporting
dirty modified content.  Fixed by reseting the the master branch of each
repository submodule.

### CODE REVIEW

**Comment by hjmjohnson** [comment]
FYI:  I don't understand how the submodules work in this example.  They always seem to cause 
```
On branch fix-sphinxexamples-build-20190314
Your branch and 'origin/fix-sphinxexamples-build-20190314' have diverged,
and have 2 and 3 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   breathe (new commits)
	modified:   gitstats (new commits)
	modified:   sphinx-bootstrap-theme (new commits)
```

When not syncronized with the master branch.

**Comment by thewtex** [comment]
If I recall correctly, there is an incompatibilty with `breathe` master and ITK Doxygen XML.

**Comment by hjmjohnson** [comment]
How do I avoid the git messages that constantly state that my repository is out of date due to the submodules?

**Comment by thewtex** [comment]
`git submodule update --init --recursive` ?

**Comment by hjmjohnson** [comment]
I tried that it did not seem to work.

**Comment by hjmjohnson** [comment]
Fixed in a different commit.

**Pull request closed without merging**
