### PR TITLE
DOC: updating comments to reflect actual behavior

### PR DESCRIPTION
**Pull request by dzenanz**

### CODE REVIEW

**Comment by dzenanz** [comment]
The failing tests were failing before this PR.

**Comment by hjmjohnson** [comment]
Are the failing tests related to #130 ?

**Comment by dzenanz** [comment]
Most, if not all of them:
```text
97% tests passed, 18 tests failed out of 595

Label Time Summary:
RUNS_LONG    =  42.71 sec*proc (3 tests)

Total Test time (real) = 179.56 sec

The following tests FAILED:
	248 - ApplyAColormapToAnImageTestBaselineComparisonPython (Failed)
	252 - ApplyAColormapToAnImageTestPython (Failed)
	535 - MultiphaseChanAndVeseSparseFieldLevelSetSegmentationTestBaselineComparison (Failed)
	536 - SinglephaseChanAndVeseSparseFieldLevelSetSegmentationTestBaselineComparison (Failed)
	537 - SinglephaseChanAndVeseSparseFieldLevelSetSegmentation2TestBaselineComparison (Failed)
	540 - MultiphaseChanAndVeseSparseFieldLevelSetSegmentationTest (Failed)
	541 - SinglephaseChanAndVeseSparseFieldLevelSetSegmentationTest (Failed)
	542 - SinglephaseChanAndVeseSparseFieldLevelSetSegmentation2Test (Failed)
	574 - SegmentWithWatershedImageFilterTest01BaselineComparisonPython (Failed)
	576 - SegmentWithWatershedImageFilterTest02BaselineComparisonPython (Failed)
	578 - SegmentWithWatershedImageFilterTest03BaselineComparisonPython (Failed)
	580 - SegmentWithWatershedImageFilterTest04BaselineComparisonPython (Failed)
	582 - SegmentWithWatershedImageFilterTest05BaselineComparisonPython (Failed)
	589 - SegmentWithWatershedImageFilterTest01Python (Failed)
	590 - SegmentWithWatershedImageFilterTest02Python (Failed)
	591 - SegmentWithWatershedImageFilterTest03Python (Failed)
	592 - SegmentWithWatershedImageFilterTest04Python (Failed)
	593 - SegmentWithWatershedImageFilterTest05Python (Failed)
SetCTestConfiguration:BuildDirectory:/home/vsts/work/1/ITKEx-bld
```

**Comment by hjmjohnson** [comment]
@dzenanz We (i.e. @mseng10) could assist with making those test pass, but we are currently at an impasse regarding what the next steps are to resolve this problem.

**Comment by dzenanz** [comment]
The watershed failures are almost certainly related to https://github.com/InsightSoftwareConsortium/ITK/pull/187. And I think I updated the baselines in https://github.com/InsightSoftwareConsortium/ITKExamples/pull/103. If baselines need to be updated again, it would be interesting to know why.

**Comment by dzenanz** [comment]
Chan and Vese might be related to this [patch](https://review.source.kitware.com/%23/c/23672/) and [discussion](https://discourse.itk.org/t/otsumultiplethresholdsimagefilter-creates-asymmetric-classes-for-a-symmetric-distribution/354).

**Pull request merged**
