### PR TITLE
ENH: Add SetDefaultNumberOfThreads

### PR DESCRIPTION
**Pull request by thewtex**
Addresses: https://github.com/InsightSoftwareConsortium/ITK/issues/113

### CODE REVIEW

**Comment by thewtex** [comment]
@mrocklin please take a look

**Comment by mrocklin** [comment]
From a Python user's perspective I would prefer an API like ...


```python
import itk
itk.set_nthreads(4)
```

There are a few other libraries (blosc comes to mind) that do something similar.

However, with proper documentation what's here also works. I imagine that the sorts of people who are going to want to change the default number of threads are also going to have a decently high tolerance for writing lots of code.

Thank you all for working on this.

**Comment by mrocklin** [comment]
Yeah, that was my guess as to what was happening.  Thought I'd mention it anyway.  Thanks all!

**Comment by dzenanz** [comment]
It should not be hard to implement. A stand-alone function `itk::set_nthreads`:
```C++
void 
set_nthreads(ThreadIdType numberOfThreads)
{
  itk::MultiThreaderBase::SetGlobalDefaultNumberOfThreads(numberOfThreads);
}
```
should be about enough.

**Comment by dzenanz** [comment]
While such a function wouldn't make much sense in C++, we could make it available only in Python. Thoughts?

**Comment by thewtex** [comment]
Thanks for the reviews!

The CI failures are unrelated, so merging.

If there is demand for it, we could add `itk.set_nthreads` by defining it in [`itkExtras.py`](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Wrapping/Generators/Python/itkExtras.py).

It would look like:

```
def set_nthreads(number_of_threads):
    threader = itk.MultiThreaderBase.New()
    threader.SetGlobalDefaultNumberOfThreads(number_of_threads)
```

**Pull request merged**
