### PR TITLE
GitHub actions

### PR DESCRIPTION
**Pull request by hjmjohnson**

### CODE REVIEW

**Comment by hjmjohnson** [comment]
@mseng10 I needed to add a patch set to get the linting to pass.

**Comment by mseng10** [comment]
@hjmjohnson Thank you!

**Comment by hjmjohnson** [comment]
@mseng10  Have you looked at these failures?

**Comment by mseng10** [comment]
@hjmjohnson Yes. I have made changes and pushed them to my forked repo. More specifically, I have swapped the order of the last 2 commits and changed the most recent to a WIP. My current changes should allow the `build-test-cxx` job to work.

Once we have this working we can begin testing Python builds.

**Comment by mseng10** [comment]
@hjmjohnson I have updated the TODO list in #159 to adhere to the process I plan to take for this PR.

**Comment by thewtex** [comment]
Awesome!

**Comment by hjmjohnson** [comment]
@mseng10 The dashboard that shows the warnings are available here:

https://open.cdash.org/viewBuildError.php?type=1&buildid=6539803

In general the CI builds are reported under the "Experimental builds" section of https://open.cdash.org/index.php?project=Insight

**Comment by mseng10** [comment]
@hjmjohnson Just an update, I have Ubuntu and Mac builds working on my forked repo. Windows is currently broken. The only tests that pass for Windows are ones that do not work with any form of data. In addition, Windows passes all tests when built inside ITK, but only fails when built separately.

**Comment by mseng10** [comment]
@hjmjohnson Please force push my recent changes from this [branch](https://github.com/mseng10/ITKExamples/tree/github-actions). This has been rebased with the recent changes (as of now).

@thewtex The documentation build has been disabled due to many warnings being thrown. A number of them are strictly styling/syntax and have been been fixed in one my forked branches. However, roughly 200 warnings mentioned in #165 are preventing the breathelink to not properly reference the classes being used per example. I am unsure of a solution at this time, but I think merging these changes for now will allow users to test their code and we can save the documentation build in a future issue.

**Comment by thewtex** [comment]
@mseng10 awesome!! Sounds like a huge step forward :climbing:

**Pull request merged**
