### PR TITLE
ENH: Add macOS Azure Pipelines configuration

### PR DESCRIPTION
**Pull request by thewtex**

### CODE REVIEW

**Comment by kaylangan** [comment]
I'm a Program Manager on Azure Pipelines. Let me know if you have any questions or suggestions. I'm happy to help!

**Comment by thewtex** [comment]
Hi @kaylangan, thanks for reaching out!

I am trying Azure Pipelines for our community-driven scientific open source project:
- http://www.itk.org/ 
- https://www.frontiersin.org/articles/10.3389/fninf.2014.00013/full

So far, I love it! It solves so many problems that exist for scientific library continuous integration testing. In particular, the cross-platform test systems, C/C++ compiler capability, and long build times are wonderful. Thank you!

Could you please help me with the following issues?:

- On macOS, the build directory is long, which results in very long absolute paths for our builds:

  https://open.cdash.org/testDetails.php?test=689064392&build=5547048

Do you have any suggestions on how to use shorter paths?

- Could our account, `itkrobot`, https://dev.azure.com/itkrobot/, please get more build agents? We typically have a lot of community activity. See e.g. our current Gerrit activity,

  http://review.source.kitware.com/#/q/status:merged

and I think we will use the current 10 agents pretty quickly if we adopt Azure Pipelines for the main repository.

**Comment by thewtex** [comment]
Rebasing on `master`...

**Comment by thewtex** [comment]
@kaylangan we improved the build to work with the macOS agent build directory, but help with more build agents would still be welcome :-)

**Comment by kaylangan** [comment]
@thewtex I'm glad you were able to get the build going on the macOS agent!

I looked at your Gerrit activity and I think you should have more than enough resources with 10 parallel pipelines. Have you been running into issues with the limits? Are you planning on adding more projects or builds?

**Comment by thewtex** [comment]
@kaylangan a much larger load is anticipated if Azure Pipelines are adopted for the main repository:

  https://github.com/InsightSoftwareConsortium/ITK

-- there are more contributions and the builds are significantly longer.

**Comment by kaylangan** [comment]
@thewtex I see. Does [this](http://review.source.kitware.com/#/q/status:merged) not include the ITK reviews that would need builds? I had assumed it did; it looked like max 10-12 per day (and <5 on average).

If the concern is around time limits, [you can set the time limit to be longer than an hour](http://review.source.kitware.com/#/q/status:merged) and as long as 6 hours.

**Comment by thewtex** [comment]
> @thewtex I see. Does [this](http://review.source.kitware.com/#/q/status:merged) not include the ITK reviews that would need builds? I had assumed it did; it looked like max 10-12 per day (and <5 on average).

Yes, currently there around 10-12 commits per working day. Each one of these commits goes through approximately 3-4 revisions (Patch Sets) as the contributor replies to reviews and addresses issues identified by CI testing. Here is the distribution:

image

from: https://www.frontiersin.org/articles/10.3389/fninf.2014.00013/. Each change is tested on macOS / Linux / Windows and some changes also get builds for features like Python wrapping. So, current ballpark is: 10 commits * 3 revisions * 3 build systems  = 90 builds / days. These are not concurrent, but they do not count extra builds, like Python, or increased participation from moving to GitHub :-) :octocat: 

> If the concern is around time limits, you can set the time limit to be longer than an hour and as long as 6 hours.

This is a fantastic!!

**Comment by kaylangan** [comment]
Ah, I see. Unfortunately, right now, we won't be able to offer your project additional pipelines. We're currently making exceptions only for really, really large projects that have a sustained need for more than 10 pipelines. I know that's probably not what you were hoping to hear.

That said, if you're really strapped for resources, you can hook up your GitHub org to multiple Azure DevOps orgs, so if you wanted to map each of your repos to their own Azure DevOps org that could help capacity for your main project.

**Pull request merged**
