### PR TITLE
ENH: update the super-build tag to ITKv5.0.0

### LINKED ISSUE #99: Update ITK Superbuild version to 5.0 RC 2

### PR DESCRIPTION
**Pull request by dzenanz**
Closes #99.

### CODE REVIEW

**Comment by dzenanz** [comment]
Failed tests:
```text
ProcessA2DSliceOfA3DImageTestBaselineComparisonPython (Failed)
ProcessA2DSliceOfA3DImageTestPython (SEGFAULT)
AdaptiveHistogramEqualizationImageFilterTest01BaselineComparison (Failed)
AdaptiveHistogramEqualizationImageFilterTest01BaselineComparisonPython (Failed)
SegmentWithWatershedImageFilterTest01BaselineComparison (Failed)
SegmentWithWatershedImageFilterTest01BaselineComparisonPython (Failed)
```
Interestingly, only the python version of `ProcessA2DSliceOfA3DImageTest` fails, due to crashing. The other two filters probably just need baseline updates.

**Comment by dzenanz** [comment]
Of course, but it can be done after the feature freeze. I am working on other things right now.

**Comment by dzenanz** [comment]
I found a new problem: https://github.com/InsightSoftwareConsortium/ITK/issues/960

**Comment by dzenanz** [comment]
@blowekamp If not better solution is found, is an increase of comparison tolerance a good solution to  InsightSoftwareConsortium/ITK#960? The PRs are piling up here, we should do something about this soon. See @hjmjohnson's PR #107.

**Comment by blowekamp** [comment]
Relaxing the tolerance with the "toleranceIntensity=1", I think would do the trick.

**Comment by fbudin69500** [comment]
When using ITK from [this PR](https://github.com/InsightSoftwareConsortium/ITK/pull/962), the test `ProcessA2DSliceOfA3DImageTestPython` and `ProcessA2DSliceOfA3DImageTestBaselineComparisonPython` pass locally. However, for them to pass without hacking requires generating new Python packages once the PR mentioned above is merged since ITK Python is installed from PyPI.

**Comment by hjmjohnson** [comment]
Can we push this for now?  The python should start passing after PyPi is updated.

**Comment by blowekamp** [comment]
I updated the PR with my recommendation to adjust the tolerance.

**Comment by fbudin69500** [comment]
When the tests for `AdaptiveHistogramEqualizationImageFilter` and `SegmentWithWatershedImageFilterTest` are passing, this will be good to merge.

**Comment by dzenanz** [comment]
Only Python problem remains after @blowekamp's commit. Merging.

**Pull request merged**
